In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import csv

In [2]:
from sklearn.linear_model import SGDClassifier,LogisticRegression
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import log_loss
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier, GradientBoostingClassifier

In [3]:
df=pd.read_csv('train.csv',parse_dates=['Dates'])#878049

In [4]:
X_X=df.X
X_Y=df.Y

In [5]:
lc1=preprocessing.LabelEncoder()
X_DayofWeek = pd.DataFrame(lc1.fit_transform(df.DayOfWeek))
lc2=preprocessing.LabelEncoder()
X_PdDistrict = pd.DataFrame(lc2.fit_transform(df.PdDistrict))

In [6]:
minute = df.Dates.dt.minute
X_Time = df.Dates.dt.hour*60+minute
X_StreetCorner = df['Address'].str.contains('/').map(int)
X_Block = df['Address'].str.contains('Block').map(int)

In [7]:
year = df.Dates.dt.year
month = df.Dates.dt.month
day = df.Dates.dt.day
hour = df.Dates.dt.hour

In [8]:
labelcoder=preprocessing.LabelEncoder()

In [9]:
X_Category=labelcoder.fit_transform(df.Category)
Y_Train=pd.DataFrame(np.array(X_Category))

In [10]:
X_Train=pd.concat([year,month,day,hour,X_Time,X_DayofWeek,X_PdDistrict,X_X,X_Y,X_StreetCorner,X_Block],axis=1)

In [11]:
X_Train

,Dates,Dates,Dates,Dates,Dates,0,0,X,Y,Address,Address
0,2015,5,13,23,1433,6,4,-122.425892,37.774599,1,0
1,2015,5,13,23,1433,6,4,-122.425892,37.774599,1,0
2,2015,5,13,23,1413,6,4,-122.424363,37.800414,1,0
3,2015,5,13,23,1410,6,4,-122.426995,37.800873,0,1
4,2015,5,13,23,1410,6,5,-122.438738,37.771541,0,1
5,2015,5,13,23,1410,6,2,-122.403252,37.713431,0,1
6,2015,5,13,23,1410,6,2,-122.423327,37.725138,1,0
7,2015,5,13,23,1410,6,0,-122.371274,37.727564,1,0
8,2015,5,13,23,1380,6,6,-122.508194,37.776601,0,1
9,2015,5,13,23,1380,6,1,-122.419088,37.807802,1,0
10,2015,5,13,22,1378,6,1,-122.419088,37.807802,1,0
11,2015,5,13,22,1350,6,8,-122.487983,37.737667,0,1
12,2015,5,13,22,1350,6,9,-122.412414,37.783004,1,0
13,2015,5,13,22,1326,6,4,-122.432915,37.784353,1,0
14,2015,5,13,22,1320,6,0,-122.397744,37.729935,0,1
15,2015,5,13,22,1320,6,0,-122.383692,37.743189,0,1
16,2015,5,13,22,1320,6,9,-122.412597,37.783932,1,0
17,2015,5,13,21,1315,6,2,-122.421682,37.742822,1,0
18,2015,5,13,21,1300,6,0,-122.386401,37.738983,1,0
19,2015,5,13,21,1290,6,9,-122.412250,37.782556,0,1
20,2015,5,13,21,1290,6,2,-122.449389,37.742669,0,1
21,2015,5,13,21,1277,6,2,-122.420272,37.747332,0,1
22,2015,5,13,21,1271,6,9,-122.412250,37.782556,0,1
23,2015,5,13,21,1271,6,9,-122.412250,37.782556,0,1
24,2015,5,13,21,1270,6,4,-122.436049,37.799841,1,0
25,2015,5,13,21,1260,6,9,-122.410509,37.786043,0,1
26,2015,5,13,21,1260,6,4,-122.431018,37.787388,0,1
27,2015,5,13,21,1260,6,2,-122.423656,37.732556,0,1
28,2015,5,13,21,1260,6,8,-122.475773,37.744919,1,0
29,2015,5,13,20,1256,6,8,-122.499787,37.748518,0,1
...,...,...,...,...,...,...,...,...,...,...,...
878019,2003,1,6,2,157,1,7,-122.410294,37.782231,1,0
878020,2003,1,6,2,152,1,4,-122.420642,37.781961,1,0
878021,2003,1,6,2,144,1,4,-122.431191,37.767595,1,0
878022,2003,1,6,2,136,1,3,-122.419516,37.763429,1,0
878023,2003,1,6,2,135,1,9,-122.416894,37.784286,0,1
878024,2003,1,6,2,129,1,5,-122.437781,37.775483,0,1
878025,2003,1,6,2,126,1,0,-122.387710,37.740674,1,0
878026,2003,1,6,2,126,1,0,-122.387710,37.740674,1,0
878027,2003,1,6,2,120,1,7,-122.409708,37.782828,0,1
878028,2003,1,6,2,120,1,7,-122.410294,37.782231,1,0
878029,2003,1,6,1,114,1,9,-122.434423,37.779193,0,1
878030,2003,1,6,1,114,1,9,-122.434423,37.779193,0,1
878031,2003,1,6,1,110,1,0,-122.390417,37.735593,1,0
878032,2003,1,6,1,96,1,4,-122.423031,37.785482,1,0
878033,2003,1,6,1,90,1,6,-122.391668,37.757793,0,1
878034,2003,1,6,1,90,1,6,-122.391668,37.757793,0,1
878035,2003,1,6,0,55,1,4,-122.431046,37.783030,0,1
878036,2003,1,6,0,55,1,4,-122.431046,37.783030,0,1
878037,2003,1,6,0,55,1,4,-122.431046,37.783030,0,1
878038,2003,1,6,0,42,1,9,-122.411519,37.786941,1,0
878039,2003,1,6,0,40,1,4,-122.420692,37.790577,1,0
878040,2003,1,6,0,33,1,3,-122.414073,37.751685,0,1
878041,2003,1,6,0,31,1,6,-122.472985,37.782552,1,0
878042,2003,1,6,0,20,1,0,-122.389769,37.730564,0,1
878043,2003,1,6,0,20,1,0,-122.389769,37.730564,0,1
878044,2003,1,6,0,15,1,8,-122.459033,37.714056,1,0
878045,2003,1,6,0,1,1,2,-122.447364,37.731948,0,1
878046,2003,1,6,0,1,1,7,-122.403390,37.780266,1,0
878047,2003,1,6,0,1,1,7,-122.390531,37.780607,1,0
878048,2003,1,6,0,1,1,0,-122.394926,37.738212,0,1

In [12]:
df2=pd.read_csv('test.csv',parse_dates=['Dates'])

In [13]:
X_X=df2.X
X_Y=df2.Y

In [14]:
X_DayofWeek = pd.DataFrame(lc1.transform(df2.DayOfWeek))
X_PdDistrict = pd.DataFrame(lc2.transform(df2.PdDistrict))

In [15]:
minute = df2.Dates.dt.minute
X_Time = df2.Dates.dt.hour*60+minute
X_StreetCorner = df2['Address'].str.contains('/').map(int)
X_Block = df2['Address'].str.contains('Block').map(int)

In [16]:
year = df2.Dates.dt.year
month = df2.Dates.dt.month
day = df2.Dates.dt.day
hour = df.Dates.dt.hour

In [17]:
Y=np.array(df.Category.values)

In [18]:
X_Test=pd.concat([year,month,day,hour,X_Time,X_DayofWeek,X_PdDistrict,X_X,X_Y,X_StreetCorner,X_Block],axis=1)
X_Test=X_Test.fillna(value=0)

In [21]:
#clf=SGDClassifier(loss='log')
#clf = LogisticRegression(C=1e5)
#clf = MultinomialNB()
#clf = BernoulliNB()
clf=RandomForestClassifier(n_estimators=20,verbose=3)
clf.set_params(min_samples_split=1000)

In [22]:
clf.fit(X_Train,Y)

building tree 1 of 20
building tree 2 of 20
building tree 3 of 20
building tree 4 of 20
building tree 5 of 20
building tree 6 of 20
building tree 7 of 20
building tree 8 of 20
building tree 9 of 20
building tree 10 of 20
building tree 11 of 20
building tree 12 of 20
building tree 13 of 20
building tree 14 of 20
building tree 15 of 20
building tree 16 of 20
building tree 17 of 20
building tree 18 of 20
building tree 19 of 20
building tree 20 of 20

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:   53.4s finished

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=None, verbose=3,
            warm_start=False)

In [23]:
Y_Test=np.array(clf.predict_proba(np.array(X_Test)))

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:   33.7s finished

In [24]:
maxes=[clf.classes_[np.argmax(Y)] for Y in Y_Test]
np.unique(maxes).size

37

In [ ]:
result=pd.DataFrame(Y_Test, columns=labelcoder.classes_)
result.to_csv('Result.csv', index = True, index_label = 'Id')